### ISSUE TITLE
How can I change the text size of chat? If it cannot be changed, can the function of changing the text size of the chat be added?

### ISSUE THREAD

**Issue by kokorobeats** [3dproger/AxelChat#1]
How can I change the text size of chat? If it cannot be changed, can the function of changing the text size of the chat be added?

**Comment by 3dproger** [comment]
Hey! Unfortunately, I have not yet started creating settings for customizing the appearance, so the text size cannot be changed. But I plan to do it in the future

**Comment by kokorobeats** [comment]
In addition, I hope to increase the function of always putting the program window on top

**Comment by 3dproger** [comment]
Okay, I'll take a note. This will be a pretty useful feature

**Comment by kokorobeats** [comment]
Thank you for your reply. I don’t know how to use github. Should I close the issue now?

**Comment by 3dproger** [comment]
No, it is not necessary. If necessary, I can do it myself

**Comment by 3dproger** [comment]
Thank you for your feedback! If you have any more wishes, you can safely write

**Comment by kokorobeats** [comment]
thanks
I thought about it for a while, and I hope you can add the following functions to AxelChat:
Display of new subscribers, new members, and new Super Chats
Make the background transparent
And, in order to prevent the program window from being clicked by mistake, click-through function can also be added, such as pressing a shortcut key, the program window will no longer be clicked by the mouse, and pressing the shortcut key again will restore it

**Comment by 3dproger** [comment]
Okay, I'll take note of these features too. Thank you!

**Comment by 3dproger** [comment]
Hey! I made an update, I have already done most of the proposed features. Display of new subscribers, new members, and new Super Chats did not have time to do it yet, but in plans
P.S. By the way, updates are displayed when the program starts

The full list of changes can be found here: https://github.com/3dproger/AxelChat/releases/download/0.17.0/AxelChat_v0.17.0-win64.zip

**Comment by kokorobeats** [comment]
wow! Hard work, so cool
However, I found another problem. As shown in the figure, since the text has no black borders, the characters cannot be seen clearly in some places that are too bright. Can you add black borders to the text?
![830183741](https://user-images.githubusercontent.com/70713712/131327580-dd2300c4-18ac-47de-9cb7-65ea5eb703c2.png)
![0184432](https://user-images.githubusercontent.com/70713712/131327850-2d2cb4c9-a0bc-4ac8-a8e1-cbd2f2094138.png)
![830183741](https://user-images.githubusercontent.com/70713712/131327855-18bca04d-8cc8-4de7-868e-6f12899e09c1.png)

**Comment by 3dproger** [comment]
Thanks to!
Yes, I also believe that this problem must be resolved. I will try to do it in the next update

**Comment by 3dproger** [comment]
Hey! I added a black outline in a new minor update

**Comment by 3dproger** [comment]
For YouTube display of new members, and new Super Chats also implemented in the latest update: https://github.com/3dproger/AxelChat/releases/download/0.17.2/AxelChat_v0.17.2-win64.zip

For YouTube, displaying new subscribers is very difficult to do, since YouTube provides a very inconvenient way to do this. In addition, many users disable this feature in their account settings, so most likely this feature will not appear in the near future

The feature for displaying such notifications from Twitch will be implemented in future updates whenever possible. But now this is not a priority, as there are already quite good tools for displaying such notifications for Twitch

**Comment by 3dproger** [comment]
You're welcome! I am very glad that you liked AxelChat!
