### ISSUE TITLE
Implement 7TV support

### ISSUE THREAD

**Issue by kilroy98** [3dproger/AxelChat#147]
https://7tv.app/

**Comment by 3dproger** [comment]
Hi! Added support for BetterTTV, FrankerFaceZ and 7TV

**Comment by kilroy98** [comment]
That's good news, thanks. It is a pity that animated emoticons are not supported (there are a lot of them). And it seems like Twitch itself also has support for animated emoticons, if I'm not mistaken.

**Comment by 3dproger** [comment]
Animated emoticons are currently supported, but only in widgets. The message widget can be opened from here. Widgets are still raw but ready to use
![image](https://github.com/3dproger/AxelChat/assets/22375229/ae59d961-d0f6-4688-9c23-24411627f13d)

**Comment by kilroy98** [comment]
But it seems to me that the streamer will read messages from the main application window, and not through the widget.

**Comment by 3dproger** [comment]
Ok, I'll try to do it as best I can, but it might take a long time
