### ISSUE TITLE
Сохранять ID трансляции в отдельный ini / txt

### ISSUE THREAD

**Issue by 2ndChannel** [3dproger/AxelChat#179]
Нужно, чтобы автоматизировать AxelChat с программой, которую пишу на GM

**Comment by 3dproger** [comment]
> 
> 
> Нужно, чтобы автоматизировать AxelChat с программой, которую пишу на GM

Я так понял, сейчас это уже сделано. Файл current.ini находится рядом с папкой broadcasts, в этом файле находится вся основная информация о текущем состоянии аксельчата
Файл:
![изображение](https://user-images.githubusercontent.com/22375229/120899912-b579e700-c63a-11eb-8b70-d7551c87a19b.png)
Внутри этого файла на 14-ой строке как раз содержится id трансляции:
![изображение](https://user-images.githubusercontent.com/22375229/120899927-c1fe3f80-c63a-11eb-950e-08dfed5f8bbc.png)
