### ISSUE TITLE
Замечены вылеты у некоторых пользователей. Причина неизвестна, повтряется редко

### ISSUE THREAD

**Issue by 3dproger** [3dproger/AxelChat#18]

**Comment by 2ndChannel** [comment]
![2](https://user-images.githubusercontent.com/54940639/101219914-2d705000-369e-11eb-9bf2-9417aaabf803.png)
![1](https://user-images.githubusercontent.com/54940639/101219920-2ea17d00-369e-11eb-817a-0a90be0b1e05.png)
После закрытия программы

**Comment by 3dproger** [comment]
С 0.15.0 не актуально
