### ISSUE TITLE
Add VK support 

### ISSUE THREAD

**Issue by kilroy98** [3dproger/AxelChat#181]
I mean vk.com

_And one question - can I write in russian? Or is it better to write in english?_

**Comment by 3dproger** [comment]
Ok, I'll try to make VK support. It is preferable to write in English, but writing in Russian is not forbidden

**Comment by kilroy98** [comment]
Okay, thanks for the answer and your work :)

**Comment by 3dproger** [comment]
You're welcome :)

**Comment by 3dproger** [comment]
Hello! Added support for VK as "VK Video" in the latest update
