### ISSUE TITLE
RESET? 

### ISSUE THREAD

**Issue by question123433** [3dproger/AxelChat#204]
hi guys, 

how can i reset everything? i made it transparent and clicktrouhgh able and now i can't get into the settings again. unzipping doesn't help either because everything is saved somewhere....  please help me

other question: is tiktok integration planned or someone has get it done somewho? 

thanks a lot

**Comment by 3dproger** [comment]
Hello,

There is an alternative way to open the settings by right clicking on the AxelChat icon in the system tray:

![изображение](https://github.com/3dproger/AxelChat/assets/22375229/ad71f3e0-4e66-4a38-9011-9cb0fceef3b0)

If you need a full reset of the settings, then this is done through the registry editor. Find regedit.exe in Start, find section ```HKEY_CURRENT_USER/SOFTWARE/Axel_k, 3dproger/AxelChat``` and delete the ```AxelChat``` folder:

![изображение](https://github.com/3dproger/AxelChat/assets/22375229/32ff242e-2c72-4d04-b6b6-a1bb6abf6546)

Integration with TikTok is planned, but for some reason it is not known when it will be possible to do this.

 Best wishes 😉
