### ISSUE TITLE
Twitch nick not visible

### ISSUE THREAD

**Issue by shevernitskiy** [3dproger/AxelChat#340]
One twitch nick (grey without avatar) not visible.

<img width="364" alt="image" src="https://github.com/3dproger/AxelChat/assets/28886342/af452edb-18d0-4801-bd4d-2743bd4a9716">

**Comment by 3dproger** [comment]
Thanks for the message, I'll fix it as soon as possible

**Comment by 3dproger** [comment]
Hi!

If this is still relevant, does the bug still appear? I have not been able to reproduce it for so long. Has this bug appeared lately?

**Comment by shevernitskiy** [comment]
Can't check it atm. You can close issue. I'll reopen it later if will appear.

**Comment by 3dproger** [comment]
Okay, anyway thanks for letting me know
