### ISSUE TITLE
Why list TikTok in your app? Is it just a way to get more views to the page?

### ISSUE THREAD

**Issue by tomdevlive** [3dproger/AxelChat#344]
I notice Tiktok chat is not supported so I'm confused why you list it in your tags. I was literally heartbroken when I discorverd you did not have support for tiktok chat yet you fooled me by adding a tiktok tag.

**Comment by 3dproger** [comment]
I apologize for the confusion. Work on integration with tiktok is in progress, that's why the tag was added

**Comment by 3dproger** [comment]
Hello! This is done in the new update
