### ISSUE TITLE
7tv emotes bug, they are not shown

### ISSUE THREAD

**Issue by Kronagh** [3dproger/AxelChat#357]
After spending several minutes testing on my channel and some colleagues, we have not been able to see the 7tv emotes, if you could take a look at it you would help us a lot. I have tried Youtube, Kick and Twitch. Does not work with general or custom emotes

**Comment by 3dproger** [comment]
Hello! This problem is known. This will be fixed in the next update. Thanks for the feedback!

**Comment by 3dproger** [comment]
Hello! This has been fixed in the latest patch

**Comment by Kronagh** [comment]
excellent work. Now I can see the 7tv emotes. Any option to see the animated emotes and be able to mouse over the emote to see its name?

**Comment by 3dproger** [comment]
Animated emotes currently only work in web widgets (see window `Settings`->category `Widgets`). This has not yet been done in the main window. Showing emotes names on mouseover is a good idea. I'll try to do this in the future. I created a separate issue for this: https://github.com/3dproger/AxelChat/issues/368
