### ISSUE TITLE
Add Support VimmTV

### ISSUE THREAD

**Issue by NekoSuneVR** [3dproger/AxelChat#358]
VimmTV uses Websockets from `wss://chat.vimm.tv:9001/ws/chat/CHANNELNAMEHERE/`

you need keep ping server 

`{ 'mtype': 'signal', 'message': '', 'chatter': CHANNELNAMEHERE, 'channel': CHANNELNAMEHERE }`

response data 

`{ 'mtype': 'message', 'message': 'hello world!', 'chatter': USERNAME, 'channel': CHANNELNAMEHERE, prefix: '[dev]' }`

Prefixes are 
```
'[dev]': 'developer',
'[op]': 'admins',
'[mod]': 'moderators',
'[bot]': 'bot',
'[sup]': 'supporter',
'[prem1]': 'premiumT1',
'[prem2]': 'premiumT2',
'[prem3]': 'premiumT3',
'[sub1]': 'subscriber',
```

hope gives you enough info add in?

im Lib Dev to Vimm for NodejS if ever want peak code to add in your multi chat `https://github.com/NekoSuneVR/Vimm-Chat-Lib/blob/main/lib/chat.js`

**Comment by 3dproger** [comment]
Oh, hi! Thanks for the information, I'll try to do it

**Comment by 3dproger** [comment]
Hello! This is done in the latest update!
