### ISSUE TITLE
VIMM: add emotes

### ISSUE THREAD

**Issue by 3dproger** [3dproger/AxelChat#362]

**Comment by NekoSuneVR** [comment]
not sure was lookign at emotes, emotes endpoint is https://vimm.tv/api/v0/emojifier/USERNAME for example https://vimm.tv/api/v0/emojifier/chisdealhd

they finding string as :faver: and print as url in html format

incase dont know and is in as array so have to find match string for grab url

just for update on emotes side

**Comment by NekoSuneVR** [comment]
but each user who chat in channel has emotes access and global emotes in there too so all in one just they personal or someone else emotes stores as selected chatter username

**Comment by 3dproger** [comment]
Hello! Thank you, this is useful information

**Comment by NekoSuneVR** [comment]
no worries i used work with vimm and i know endpoints and im basely close friends 2 devs there so i get all early api access endpoints. but if need anythign for vimm ping me in it i see i find any private docs on it i arcrived i used have.

**Comment by 3dproger** [comment]
Okay, thanks, I'll let you know when I need any information

**Comment by 3dproger** [comment]
Hello! This is done in the new update
