### ISSUE TITLE
Empty chat on startup

### ISSUE THREAD

**Issue by kilroy98** [3dproger/AxelChat#371]
Give the opportunity to choose whether old messages will be displayed after launching AxelChat. For the most part, this is necessary because of Trovo (I don’t know about other platforms), because there messages are saved for 24 hours or even longer (if I’m not mistaken) and it turns out that when you launch AxelChat, old messages are displayed from Trovo, which is a little confusing. Yes, it is possible to manually clear the chat, but it seems to me that this function is slightly for other cases and it will be more convenient if there is a separate setting.

======
Although I think that it is still worth making it forced, and not with the option of choice.

**Comment by 3dproger** [comment]
Hello! This is a known issue and is planned to be fixed. Perhaps this can be customized and by default old messages will not be visible

**Comment by 3dproger** [comment]
Hello! This is done in the new update
