### ISSUE TITLE
When there is a large flow of messages, autoscroll in the main window stops working

### ISSUE THREAD

**Issue by 3dproger** [3dproger/AxelChat#383]

**Comment by MCas86** [comment]
I haven't noticed this issue and I've been watching large streams with AxelChat. Only Twitch and YT though. Is there a certain platform that's causing this or is the main issue not pinpointed yet?

**Comment by 3dproger** [comment]
No, there is no specific platform. But I noticed this with streamer https://kick.com/xqc and other similar popular ones on Kick or Twitch. There is a really large flow of messages in his chat
