### ISSUE TITLE
Activating Stay On Top breaks the Chat Window 

### ISSUE THREAD

**Issue by DannyCapM8** [3dproger/AxelChat#384]
I turned on the Stay On Top, and now AxelChat won't allow me to click on it, can't enter the setting, etc. Clicking on the Axelchat at all acts as if it doesn't exist and clicks whatever is in the background.

![image](https://github.com/3dproger/AxelChat/assets/140923841/c29def2a-a651-4e9e-8896-1745e010ce4b)

**Comment by MCas86** [comment]
Do you have "Ignore Mouse" enabled? It seems like you may.

Hopefully you still can see the icon in your tray and if you right click, you can uncheck "ignore mouse"

![image](https://github.com/3dproger/AxelChat/assets/7511687/128ef7d9-48dd-4411-adab-4d413b7a5526)

**Comment by DannyCapM8** [comment]
![image](https://github.com/3dproger/AxelChat/assets/140923841/312aec88-1b05-4ea2-ab00-9d9334c3f6fe)

oh my god I'm so fucking dumb, thank you!

**Comment by 3dproger** [comment]
Oops, that's my problem, since I still haven't gotten around to making a tutorial😅
