### ISSUE TITLE
Tiktok Error

### ISSUE THREAD

**Issue by animetrom** [3dproger/AxelChat#448]
I don't know if I'm doing something wrong, but for some reason the tiktok chat isn't working.
Can you help me?

**Comment by animetrom** [comment]
.

**Comment by 3dproger** [comment]
Hello! Problems connecting to TikTok have already disappeared? If yes, then everything is fine. If not, then you don’t have to close the issue

**Comment by animetrom** [comment]
@3dproger Solved, partially yes, but now I'm having a problem where, today, I did a live on several platforms, including Tiktok, where there were 3 viewers who sent a message in the chat, but for some reason it didn't go up on axelchat, just one viewer.
Do you know what it could be?

**Comment by 3dproger** [comment]
While it’s hard to say what’s wrong, I’ll try to figure it out

**Comment by 3dproger** [comment]
I managed to fix this problem. In the latest update you can download: https://github.com/3dproger/AxelChat/releases/tag/0.36.3-beta

**Comment by animetrom** [comment]
Thanks man.
