### ISSUE TITLE
Unable to click Axelchat window

### ISSUE THREAD

**Issue by SmoresDecore** [3dproger/AxelChat#471]
I was messing with the settings of ver 0.36.1-beta. I changed the apperance of the Axelchat window, such as removing border and testing the transparency. I also removed the animation when there is no chat. I want to make sure to explain what I did because since then, I am unable to click the Axelchat window at all. It is in my task bar, I can minimise it or show it from there but if I click on the window, it clicks on whatever is behind it. I am unable to access Axelchat's settings as I am unable to right-click on it.
Where are the settings saved so I can delete them?

**Comment by SmoresDecore** [comment]
I learned about the systemtray icon. I managed to access the settings and reset. It is now working again. I will play around a bit and see if I can figure out what triggered this

**Comment by SmoresDecore** [comment]
My bad. I had activated "Ignore Mouse". No problem here

**Comment by 3dproger** [comment]
Hi, glad you managed to sort this out. I'll think about making this point more understandable, since up to this point there were people who encountered this
