### ISSUE TITLE
Rumble no longer connects to axelchat

### ISSUE THREAD

**Issue by AlphaPyxis** [3dproger/AxelChat#485]
Hey as the title says, rumble doesn't seem to be connecting to AxelChat anymore. It has an infinite loading spinning circle and never connect. Hope its fixed soon,

Thank you for your great app and continued work!

**Comment by 3dproger** [comment]
Hi! Thank you, I found the problem, I'll try to fix it soon

**Comment by 3dproger** [comment]
Fixed in last release

**Comment by AlphaPyxis** [comment]
Hey man! Thank you so much for fixing this so fast, sorry for the delay getting back to you. I was real busy! Keep up the great work man. Take care.
