### ISSUE TITLE
Nothing is Connecting After Malware Remove

### ISSUE THREAD

**Issue by 0ver1n0ut** [3dproger/AxelChat#519]
Hello,

I downloaded the latest version, and did a virus scan on it.
The scan detected malware, and quarantine it.
After that, nothing can connect to AxelChat.
Was that malware needed to function?
It shouldn't because it was TikTokConnector, and I don't use TikTok.

**Comment by 3dproger** [comment]
Hello,

Hmm... What antivirus did you use? I'll try to figure out why this happened and fix the problem. And could you send me a screenshot of the logs while you're trying to connect to something? How to open logs: `Settings->Developers->Logs`
Example:
![изображение](https://github.com/user-attachments/assets/0f23d497-6eb3-49c8-9464-80cb302df81a)

**Comment by 0ver1n0ut** [comment]
I use Malwarebytes.
![Screenshot 2024-08-23 181535](https://github.com/user-attachments/assets/5ba9c3d3-9a8b-4259-bead-74089ca6aed1)

**Comment by 3dproger** [comment]
Ok, thanks for the info. It looks like this antimalware deleted a couple of files needed to work with the connection although this is not a virus. Most likely, the antimalware did not like that these files are outdated so they may be vulnerable. I will try to fix this in one of the future updates

**Comment by 0ver1n0ut** [comment]
My pleasure. So in the meantime just wait for the new update?

**Comment by 3dproger** [comment]
For now I can offer three options:
* Wait for the update with the fix 
* Download AxelChat again and add the folder with AxelChat to the exceptions in the antimalware, if you trust it of course
* Download AxelChat again and for now, use another antimalware

UPD: added third option

**Comment by 0ver1n0ut** [comment]
Thank you, I will wait for the update.

**Comment by 3dproger** [comment]
Another user has a similar problem. What's interesting is that this problem only occurs in versions 0.37.2, 0.37.3 and 0.37.4 for him. However, in 0.37.1 and below everything works. If you don't mind, could you check version 0.37.1 to see if it works? This will be very helpful in solving the problem. Download link: https://github.com/3dproger/AxelChat/releases/download/0.37.1/AxelChat_v0.37.1-win64.zip

**Comment by 0ver1n0ut** [comment]
This version is working perfectly fine and no viruses.

**Comment by 3dproger** [comment]
Great, that means we're close to solving the problem. Thanks for your help!

**Comment by 50andBad** [comment]
@3dproger I dont know if this is related, but I couldnt connect to twitch on my windows 10 machine until I went back to version 0.37.1 - all works fine with this version,

**Comment by 3dproger** [comment]
> @3dproger I dont know if this is related, but I couldnt connect to twitch on my windows 10 machine until I went back to version 0.37.1 - all works fine with this version,

Thank you, this is also important information

**Comment by 3dproger** [comment]
I have released 0.37.5. But I am not sure yet that this problem is solved. But if it works, it will be great

**Comment by 50andBad** [comment]
> I have released 0.37.5. But I am not sure yet that this problem is solved. But if it works, it will be great

Just tested and still same issue.
Tried both methods.   thanks for trying though x

**Comment by Aeon1704** [comment]
I had SSL TLS troubles too with version 0.37.5, but version 0.37.1 went without troubles. No Viruses prior to installation. Maybe something wrong with .dll files?

But it kinda feels that this Websocket with ws:\\ URL breaks everything.

**Comment by 3dproger** [comment]
> Maybe something wrong with .dll files?

Yes, there is a suspicion that something is wrong with this. Although, since version 0.37.1 the DLLs `libssl-1_1-x64.dll` and `libcrypto-1_1-x64.dll` have not changed. Usually, such errors occur when these two DLLs are missing. Do you have these DLLs next to the `AxelChat.exe`?

![изображение](https://github.com/user-attachments/assets/082980b5-119a-4d95-abc3-f03e49becc82)

**Comment by 3dproger** [comment]
> But it kinda feels that this Websocket with ws:\ URL breaks everything.

This is unlikely because the websocket has been present in the AxelChat for a long time, since widgets appeared, and there have never been such problems

**Comment by 3dproger** [comment]
I made a small update `0.37.6-beta`. In it I made the output in the log more detailed information about SSL. And if there are any errors, it will be visible there.

If everything is OK then the messages will be like this:
![изображение](https://github.com/user-attachments/assets/7563dc49-5c95-41db-9e62-59bc5ceabda8)

And here are the messages if the required DLLs are missing:
![изображение](https://github.com/user-attachments/assets/a065f37b-b50d-4a64-970b-31c9c222a163)

You can try running this version. Most likely, the connection will still not work correctly but at least we will be able to see what the problems were. If the antimalware really deleted these DLLs, we will immediately see it in the log.

Download link: https://github.com/3dproger/AxelChat/releases/download/0.37.6-beta/AxelChat_0.37.6-beta-win64.zip

**Comment by Aeon1704** [comment]
New Beta actually connects just fine. But in version 0.37.5 I see errors similar to 2nd screenshot. All DLLs are present. 

Funny thing is - version 0.37.5 doesn't recognize internet connection at all, saying: No internet Connection - after trying to check for updates.
(Small off-topic question)
Do you have chat widget style with alignment to bottom, instead of top? :D i.e. messages appearing from bottom.

**Comment by 3dproger** [comment]
> New Beta actually connects just fine. But in version 0.37.5 I see errors similar to 2nd screenshot. All DLLs are present.

> Funny thing is - version 0.37.5 doesn't recognize internet connection at all, saying: No internet Connection - after trying to check for updates.

This is great news! Thanks for the help! Although I still don't understand what the problem was, because the DLLs are the same. Well, I hope I'll figure it out

**Comment by 3dproger** [comment]
> (Small off-topic question)
Do you have chat widget style with alignment to bottom, instead of top? :D i.e. messages appearing from bottom.

Unfortunately, I don't have one yet. But I'm working on the ability to easily select pre-made styles including ones that align messages to the bottom

**Comment by 3dproger** [comment]
Hello again to everyone who is still here! Tell me, has your problem disappeared since version 0.37.5?

**Comment by Aeon1704** [comment]
Everything seems to be fine.

**Comment by 3dproger** [comment]
I confirm, I checked with a Malwarebytes. The problem was in `TikTokConnector.exe`, which was used in the old version of the AxelChat. Now this file has been updated and the potential threat has been eliminated, starting with AxelChat version 0.37.5

**Comment by 3dproger** [comment]
It looks like the problem is solved, I'll close this thread. If you want to write something else, you can reopen the thread or create a new one
