### ISSUE TITLE
Ссылки в чате с YouTube отображаются некорректно

### ISSUE THREAD

**Issue by 3dproger** [3dproger/AxelChat#52]

**Comment by ghostdogtm** [comment]
Отображаются как текст и не полностью, если сообщение длинное
![image](https://user-images.githubusercontent.com/15708129/97484506-73304f00-1961-11eb-819b-2b96a1902cf5.png)

**Comment by 3dproger** [comment]
Судя по всему, ютуб присылает оборванные ссылки в поле сообщения текста, а в другом месте лежит полная информация о ссылке:
![изображение](https://user-images.githubusercontent.com/22375229/97487805-69611880-196e-11eb-96da-2c30d9b094b8.png)

**Comment by 3dproger** [comment]
Исправлено в 0.16.0. Ссылки ютуба стали кликабельными
