### ISSUE TITLE
Endless stream loading indicator from Rutube and VK Video

### ISSUE THREAD

**Issue by vomitting** [3dproger/AxelChat#560]
![2024-10-04 20_16_44-Подключения](https://github.com/user-attachments/assets/72dd22f7-8cb1-446f-8036-68b1ba64d6d4)
![2024-10-04 20_17_05-Подключения](https://github.com/user-attachments/assets/f88f8d3c-04ea-4bfb-a124-cd0506f94fa9)
Hello, I can’t display chats from rutube and vk video, the endless indicator for loading information from services hangs and hangs.

Здравствуйте, не могу вывести чаты с rutube и vk video, бесконечный индикатор подгрузки информации с сервисов висит и висит.

**Comment by 3dproger** [comment]
Здравствуйте, судя по всему, Рутуб изменил вид ссылок на стрим и AxelChat пока не поддерживает такие ссылки. Я постараюсь в ближайшем обновлении это исправить. Пока что можете указывать этот идентификатор, вместо ссылки:
![изображение](https://github.com/user-attachments/assets/d79105e7-f211-4d83-99ad-888ea8990a0b)

По поводу ВК, пока что непонятно, почему не подключается, так как у меня подключилось по Вашей ссылке:
![изображение](https://github.com/user-attachments/assets/cce966ef-f7b2-45fb-8b6a-8fa4d462397d)

Если у Вас всё ещё не подключается ВК Видео, можете прислать Логи, чтобы я лучше понимал причину проблемы? Логи открываются тут:
![изображение](https://github.com/user-attachments/assets/4f895057-88b1-4b00-8c8a-e9e59ff162ca)
Можно прислать либо либо текстом, либо скриншот:
![изображение](https://github.com/user-attachments/assets/958aa893-dead-4377-bc3a-b4a6826fcb28)

**Comment by vomitting** [comment]
Понял, спасибо большое за ответ, пошёл пробовать!

**Comment by vomitting** [comment]
VK video заработал сам. Rutube - ваш метод помог! спасибо Вам большое!

**Comment by 3dproger** [comment]
В общем, сделал обнову, исправил подключение по ссылке в Рутубе)

**Comment by 3dproger** [comment]
I did an update, probably the problem with connecting to YouTube should be restored

**Comment by vomitting** [comment]
Спасибо Вам большущее!

**Comment by 3dproger** [comment]
Пожалуйста) Кстати, с ВК иногда возникает эта проблема, буду думать как её решить. А пока я закрою этот Issue. Если будут ещё вопросы, можете переоткрыть этот Issue или открыть новый)
