### ISSUE TITLE
Вылет при закрытии программы

### ISSUE THREAD

**Issue by 3dproger** [3dproger/AxelChat#60]
![изображение](https://user-images.githubusercontent.com/22375229/97493143-9b29ad80-1975-11eb-8997-d17964f8ddf5.png)

**Comment by ghostdogtm** [comment]
проверил, в общем у меня при любых раскладах ошибку эту показывает, даже если трансляция еще идет, просто закрываю чат и вот это окно.

**Comment by 3dproger** [comment]
исправлено в 0.10.0

**Comment by 2ndChannel** [comment]
Не стал дублировать, но у меня иногда после запуска через какое-то время программа виснет (надеюсь тут ты увидишь моё сообщение. пожалуйста, дай знать)

**Comment by 3dproger** [comment]
Хм, если это так, тогда переоткрою эту проблему. Нужно будет разобраться с этим

**Comment by 3dproger** [comment]
Не актуально на момент версии 0.15.0
