### ISSUE TITLE
Добавьте возможность сделать чат прозрачным для захвата его в obs

### ISSUE THREAD

**Issue by Patraskon** [3dproger/AxelChat#61]

**Comment by 3dproger** [comment]
К сожалению, сделать это в ближайшем будущем не получится из-за технических сложностей, хотя это важная функция и постараюсь её реализовать, как появится возможность. На данный момент могу посоветовать использовать фильтр Цветовой ключ, чтобы удалить фон. Хотя конечно с фоном удалится чёрный цвет со всего остального. Могу в ближайшем обновлении сделать возможность менять цвет фона, чтобы хоть как-то можно было бы избавиться от этой проблемы. Также можно пользоваться той прозрачностью, что уже есть, но вместо захвата окна использовать захват части экрана

**Comment by 3dproger** [comment]
Вот так у меня выглядит захват в обс с фильтром цветового ключа:
![изображение](https://user-images.githubusercontent.com/22375229/185443808-59cb90ea-2236-40d6-a73f-0271773ff01b.png)

**Comment by 3dproger** [comment]
Привет! Если эта информация ещё актуальна, то захватывать чат с прозрачным фоном можно с помощью источниках ОБС "Браузер". Ссылка для этого находится в окне настроек в разделе "Виджеты". В дальнейшем, появится возможность настраивать внешний вид чата, который будет отображаться таким образом
