### ISSUE TITLE
Сохранять INI в кодировке ANSI

### ISSUE THREAD

**Issue by 2ndChannel** [3dproger/AxelChat#87]
Попытался извлекать информацию из ини и столкнулся с проблемой, что гм не читает кириллицу, если ини сохранён в кодировке Юникод (вроде бы... ну в той, в которой сохраняет программа чат в версии 10 по крайней мере).
Пожалуйста, внеси это исправление в новейшее обновление. Без этого писать что-то на гм вряд ли получится

**Comment by 3dproger** [comment]
Сделано в 0.11.0
